export const FETCH_STARSHIP_SUCCESS = 'FETCH_STARSHIP_SUCCESS';
export const FETCH_STARSHIP_ERROR = 'FETCH_STARSHIP_ERROR';
export const CLEAR_STARSHIP_ERRORS = 'CLEAR_STARSHIP_ERRORS';
export const CLEAR_ACTIVE_STARSHIPS = 'CLEAR_ACTIVE_STARSHIPS';
export const SET_STARSHIP_TO_ACTIVE = 'SET_STARSHIP_TO_ACTIVE';
export const SET_FETCHING = 'SET_FETCHING';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const SET_CATEGORY = 'SET_CATEGORY';
